### PR TITLE
Initial ChatBot implementation

### PR DESCRIPTION
**Pull request by yuri-sergiichuk**
The PR is here to address https://github.com/SpineEventEngine/config/issues/403 issue.
In the PR I have drafted the initial implementation of the ChatBot applications that allows notifying Spine developers about Travis CI builds failures through the Google Chat.

The idea of the app is to use Travis CI API in order to fetch the latest master branch build status for the registered repositories and notify Spine Developers to a particular Google Chat room and thread with the build state.

### CODE REVIEW

**Review by armiol — CHANGES_REQUESTED** [review]
@yuri-sergiichuk please refer to the latest Spine build scripts and modify this project accordingly:

* Kotlin in Gradle scripts instead of Groovy;
* application version defined in a separate file;
* (perhaps, in future PRs) static code analysis is configured: Error Prone, PMD, Checkstyle;
* (consult with @dmdashenkov) there is already Gradle 6.5, but Dmitry mentioned there was an issue in their release which breaks some of our Spine plugin code.

In addition to the project setup:

* Public API must be documented.
* Avoid the wildcard imports. Use the latest inspection profile from Spine. Also, it helps to use the most recent IDEA (I am using the latest EAP at the moment) — it detects more warnings and errors, some of them even inline as you type.
* Please have a `README.md` stating the name of the application AND some details. So if you wish to speak of Micronaut, do that in the document body, not in the title. Also, choosing Java 11 needs some explanation in terms of the target deployment environment — I don't know the plan, so I am not able to comment on this matter.
* (optional) I am not sure about Log4J. To me, this is a very early decision.

**Review by armiol — CHANGES_REQUESTED** [review]
@yuri-sergiichuk I am 33% done. Please see my comments I left so far.

**Review by armiol — CHANGES_REQUESTED** [review]
@yuri-sergiichuk 75% reviewed. See my comments.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see my comments.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see my comments. More to come.

**Review by armiol — CHANGES_REQUESTED** [review]
@yuri-sergiichuk  50/142 reviewed, starting from the top. Please see my comments.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see some more. I'm climbing up with 40 files left.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see some more. With more to come soon.

**Review by armiol — COMMENTED** [review]
@yuri-sergiichuk more comments. 77/142 reviewed.

**Review by armiol — COMMENTED** [review]
@yuri-sergiichuk Done. Please see a bit more comments.

It's a good and big piece of work. I feel there was some rush when writing the code. Hope, it's not going to take a big amount of time to address the comments, as most of them are easy-to-fix.

Feel free to ask for explanation. To me, it's better to do that vocally.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see my comments. I'm done.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
In overall, I like the changes made. It's getting really better. But there's something more to be done to this code. 

Please see the first portion of my comments and questions. I'm going to continue after a short break.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see some more comments.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see some more comments.

**Review by armiol — COMMENTED** [review]
@yuri-sergiichuk please see my comments. 53/160 reviewed.

**Review by armiol — CHANGES_REQUESTED** [review]
@yuri-sergiichuk please see my comments.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see my comments.

**Review by alexander-yevsyukov — APPROVED** [review]
LGTM, with some comments and suggestions

**Pull request merged**
